-- 0004_archive_proposals — REM-emitted archival candidates (schemi.md §1.4)
--
-- Generated by the weekly REM cron; require human approval before the
-- corresponding wiki nodes are moved to `_archive/`.

CREATE TABLE archive_proposals (
    proposal_id TEXT PRIMARY KEY,                                  -- UUID or "ap-YYYY-MM-DD-NNN"
    wiki_id     TEXT NOT NULL,
    path        TEXT NOT NULL,                                     -- filesystem path of candidate
    reason      TEXT NOT NULL,                                     -- "no_recall_hit_365d" | "no_modify_180d" | …
    proposed_at TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'pending',                   -- pending | approved | rejected | expired
    decided_at  TEXT,
    decided_by  TEXT,                                              -- sender_id of approver
    selection   TEXT                                               -- JSON: partial-approve subset
);

CREATE INDEX idx_arch_status ON archive_proposals(status, proposed_at);
