// SPDX-License-Identifier: AGPL-3.0-or-later
//! Slug derivation pipeline.
//!
//! Canonical pipeline:
//!   `NFKD normalize → lowercase → fold accents to ASCII → spaces/punct → "-"`
//!   `→ strip non-[a-z0-9-] → collapse "--+" → trim leading/trailing "-"`
//!
//! Output empty ⇒ [`Error::InvalidTitle`] (the agent must pass an explicit
//! `slug`). No automatic transliteration (rejected: ICU dependency
//! weight + non-determinism). No hash fallback (would hurt Obsidian
//! navigability).
//!
//! Collision resolver: suffix `°N` from N=2 up to N=99
//! (`Error::CollisionCapExceeded` past the cap). `°` is reserved
//! for the resolver and is *not* generated by the pipeline itself — but
//! explicit slugs containing `°` (e.g. `"bilbo°2"` passed by an agent) are
//! treated as natural slugs and a further collision produces `"bilbo°2°2"`.
//!
//! Both functions are pure: no I/O, no global state, deterministic on inputs.

use unicode_normalization::UnicodeNormalization;
use unicode_normalization::char::is_combining_mark;

use crate::error::Error;

/// Derive a slug from a free-form title.
///
/// The pipeline is the literal application described in the module docs:
///
/// 1. NFKD decomposes accented Latin letters into a base letter plus
///    combining marks (e.g. `É` → `E` + U+0301).
/// 2. Combining marks (Unicode category `Mn`) are dropped silently — this
///    is the "fold accents to ASCII" step.
/// 3. Everything else is lowercased.
/// 4. ASCII `[a-z0-9]` survives; every other character (spaces,
///    punctuation, non-Latin scripts, ligatures `œ`/`ß`/`ø` that have no
///    NFKD decomposition, emoji, `°`, …) becomes a single `-`.
/// 5. Runs of `-` collapse and leading/trailing `-` is trimmed.
///
/// The pipeline explicitly rejects automatic transliteration, so characters
/// with no canonical ASCII decomposition (`œ`, `ß`, `ø`, CJK, Cyrillic, emoji) get
/// either collapsed away or turned into a dash rather than approximated.
/// When that leaves no characters, the agent is expected to supply an
/// explicit `slug`.
///
/// # Errors
///
/// Returns [`Error::InvalidTitle`] when the pipeline produces an empty
/// string. Typical triggers: empty input, whitespace only, punctuation
/// only, pure non-Latin scripts, pure emoji.
pub fn derive_slug(title: &str) -> Result<String, Error> {
    let mut out = String::with_capacity(title.len());
    // Treat "before any output" as "just emitted a dash" so a leading run
    // of non-`[a-z0-9]` collapses instead of producing a leading `-`.
    let mut last_was_dash = true;

    for c in title.nfkd() {
        if is_combining_mark(c) {
            // Step 2: dropped silently as part of accent folding.
            continue;
        }
        let c = c.to_ascii_lowercase();
        if c.is_ascii_lowercase() || c.is_ascii_digit() {
            out.push(c);
            last_was_dash = false;
        } else if !last_was_dash {
            out.push('-');
            last_was_dash = true;
        }
    }

    // Strip the (at most one) trailing `-` left by the collapse.
    if out.ends_with('-') {
        out.pop();
    }

    if out.is_empty() {
        Err(Error::InvalidTitle {
            input: title.to_owned(),
        })
    } else {
        Ok(out)
    }
}

/// Resolve a slug collision by appending `°N`.
///
/// If `base` is free (`exists(base)` returns false), returns `base` unchanged.
/// Otherwise tries `base°2`, `base°3`, … up to `base°99` and returns the
/// first candidate `exists` reports as free.
///
/// # Errors
///
/// Returns [`Error::CollisionCapExceeded`] when all 99 candidates are taken.
/// Past this point the caller is expected to surface a `409` to the agent
/// and require an explicit `slug`.
///
/// # Note on explicit `°` in `base`
///
/// `base` may itself contain `°` — for example when an agent passes
/// `slug = "bilbo°2"` as an explicit, natural slug (re-import, restore from
/// snapshot, …). The resolver treats it as opaque text: a collision on
/// `"bilbo°2"` produces `"bilbo°2°2"`. Unusual but deterministic.
pub fn resolve_collision<F>(base: &str, exists: F) -> Result<String, Error>
where
    F: Fn(&str) -> bool,
{
    if !exists(base) {
        return Ok(base.to_owned());
    }
    for n in 2u32..=99 {
        let candidate = format!("{base}°{n}");
        if !exists(&candidate) {
            return Ok(candidate);
        }
    }
    Err(Error::CollisionCapExceeded {
        base: base.to_owned(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    // ---------- derive_slug: explicit happy-path table ----------

    #[test]
    fn happy_path_ascii() {
        assert_eq!(derive_slug("Bilbo").unwrap(), "bilbo");
        assert_eq!(derive_slug("GDPR-2026").unwrap(), "gdpr-2026");
        assert_eq!(derive_slug("ADR 024").unwrap(), "adr-024");
    }

    #[test]
    fn happy_path_accents_folded() {
        assert_eq!(derive_slug("Café").unwrap(), "cafe");
        assert_eq!(derive_slug("École Normale").unwrap(), "ecole-normale");
        assert_eq!(derive_slug("naïve").unwrap(), "naive");
        assert_eq!(derive_slug("über").unwrap(), "uber");
        // 'ñ' = 'n' + combining tilde (NFKD-decomposable).
        assert_eq!(derive_slug("ñ-año").unwrap(), "n-ano");
    }

    #[test]
    fn unsupported_ligatures_become_dashes() {
        // The pipeline explicitly rejects automatic transliteration. Characters
        // with no NFKD decomposition that are also not ASCII (ligatures,
        // sharp-s, slashed-o) are treated as punctuation by the pipeline
        // and collapse to a single `-`. The agent is expected to pass an
        // explicit `slug` (e.g. "coeur", "strasse", "kobenhavn") when this
        // is undesired — the pipeline is intentionally dumb.
        assert_eq!(derive_slug("cœur").unwrap(), "c-ur");
        assert_eq!(derive_slug("Straße").unwrap(), "stra-e");
        assert_eq!(derive_slug("København").unwrap(), "k-benhavn");
    }

    #[test]
    fn whitespace_and_punct_collapse_to_single_dash() {
        assert_eq!(derive_slug("  hello  world  ").unwrap(), "hello-world");
        assert_eq!(derive_slug("hello!@#world").unwrap(), "hello-world");
        assert_eq!(derive_slug("---hello---").unwrap(), "hello");
        assert_eq!(derive_slug("a___b").unwrap(), "a-b");
        assert_eq!(derive_slug("a\tb\nc").unwrap(), "a-b-c");
    }

    #[test]
    fn lowercase_forced_b22_2() {
        // Uppercase ASCII always folded, even if filesystem is
        // case-sensitive on Linux. Prevents collisions on case-insensitive
        // macOS/Windows filesystems.
        assert_eq!(derive_slug("FooBarBaz").unwrap(), "foobarbaz");
        assert_eq!(derive_slug("HTML5").unwrap(), "html5");
    }

    // ---------- derive_slug: explicit invalid-title table ----------

    #[test]
    fn invalid_empty() {
        assert!(matches!(derive_slug(""), Err(Error::InvalidTitle { .. })));
    }

    #[test]
    fn invalid_whitespace_only() {
        assert!(matches!(
            derive_slug("   "),
            Err(Error::InvalidTitle { .. })
        ));
        assert!(matches!(
            derive_slug("\t\n"),
            Err(Error::InvalidTitle { .. })
        ));
    }

    #[test]
    fn invalid_punctuation_only() {
        assert!(matches!(
            derive_slug("---"),
            Err(Error::InvalidTitle { .. })
        ));
        assert!(matches!(
            derive_slug("!@#"),
            Err(Error::InvalidTitle { .. })
        ));
    }

    #[test]
    fn invalid_non_latin_scripts() {
        // CJK has no canonical decomposition to ASCII.
        assert!(matches!(
            derive_slug("你好"),
            Err(Error::InvalidTitle { .. })
        ));
        // Cyrillic likewise.
        assert!(matches!(
            derive_slug("привет"),
            Err(Error::InvalidTitle { .. })
        ));
        // Emoji.
        assert!(matches!(
            derive_slug("🚀🎉"),
            Err(Error::InvalidTitle { .. })
        ));
    }

    #[test]
    fn invalid_carries_input_for_audit() {
        let err = derive_slug("你好").unwrap_err();
        match err {
            Error::InvalidTitle { input } => assert_eq!(input, "你好"),
            other => panic!("expected InvalidTitle, got {other:?}"),
        }
    }

    #[test]
    fn degree_sign_becomes_dash_in_pipeline() {
        // '°' is reserved for the *collision resolver*, which runs
        // post-pipeline. Inside the pipeline `°` is just another non-alnum
        // character and collapses to `-`. The resolver only ever sees `°`
        // when the agent passes an explicit slug containing it.
        assert_eq!(derive_slug("bilbo°2").unwrap(), "bilbo-2");
    }

    // ---------- derive_slug: proptest invariants ----------

    proptest! {
        #[test]
        fn output_only_lowercase_alnum_and_hyphen(s in ".{0,256}") {
            if let Ok(slug) = derive_slug(&s) {
                for c in slug.chars() {
                    prop_assert!(
                        c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-',
                        "unexpected char {:?} in slug {:?}", c, slug
                    );
                }
            }
        }

        #[test]
        fn no_double_dash(s in ".{0,256}") {
            if let Ok(slug) = derive_slug(&s) {
                prop_assert!(!slug.contains("--"), "double dash in slug {:?}", slug);
            }
        }

        #[test]
        fn no_leading_or_trailing_dash(s in ".{0,256}") {
            if let Ok(slug) = derive_slug(&s) {
                prop_assert!(!slug.starts_with('-'), "leading dash in {:?}", slug);
                prop_assert!(!slug.ends_with('-'), "trailing dash in {:?}", slug);
            }
        }

        #[test]
        fn never_empty_when_ok(s in ".{0,256}") {
            if let Ok(slug) = derive_slug(&s) {
                prop_assert!(!slug.is_empty());
            }
        }

        /// The pipeline is idempotent on valid outputs: re-running it on a
        /// produced slug yields the same slug. This is the cheapest property
        /// that locks down “the pipeline does not bite its own tail”.
        #[test]
        fn idempotent_on_valid_output(s in ".{0,256}") {
            if let Ok(slug) = derive_slug(&s) {
                let again = derive_slug(&slug)
                    .expect("slug derived from a valid slug must still be valid");
                prop_assert_eq!(&slug, &again);
            }
        }
    }

    // ---------- resolve_collision: explicit table ----------

    #[test]
    fn collision_free_base_returns_base_unchanged() {
        let r = resolve_collision("bilbo", |_| false).unwrap();
        assert_eq!(r, "bilbo");
    }

    #[test]
    fn collision_one_existing_promotes_to_n2() {
        let r = resolve_collision("bilbo", |s| s == "bilbo").unwrap();
        assert_eq!(r, "bilbo°2");
    }

    #[test]
    fn collision_two_existing_promotes_to_n3() {
        let r = resolve_collision("bilbo", |s| matches!(s, "bilbo" | "bilbo°2")).unwrap();
        assert_eq!(r, "bilbo°3");
    }

    /// Build an `exists` closure that says yes to `bilbo` and to `bilbo°2..bilbo°upper`.
    fn taken_up_to(upper: u32) -> impl Fn(&str) -> bool {
        move |s: &str| {
            if s == "bilbo" {
                return true;
            }
            s.strip_prefix("bilbo°")
                .and_then(|n| n.parse::<u32>().ok())
                .is_some_and(|n| (2..=upper).contains(&n))
        }
    }

    #[test]
    fn collision_finds_n99_when_98_taken() {
        let r = resolve_collision("bilbo", taken_up_to(98)).unwrap();
        assert_eq!(r, "bilbo°99");
    }

    #[test]
    fn collision_cap_exceeded_when_all_99_taken() {
        let err = resolve_collision("bilbo", taken_up_to(99)).unwrap_err();
        match err {
            Error::CollisionCapExceeded { base } => assert_eq!(base, "bilbo"),
            other => panic!("expected CollisionCapExceeded, got {other:?}"),
        }
    }

    #[test]
    fn collision_explicit_degree_slug_treated_as_natural() {
        // Explicit slug "bilbo°2" is opaque. A collision on it
        // produces "bilbo°2°2", not a re-interpretation of the existing
        // suffix.
        let r = resolve_collision("bilbo°2", |s| s == "bilbo°2").unwrap();
        assert_eq!(r, "bilbo°2°2");
    }
}
